# Generated by Django 4.1.4 on 2023-03-13 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nombres')),
                ('treatment', models.CharField(max_length=200, verbose_name='Tratamiento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'testimonio',
                'verbose_name_plural': 'testimonios',
                'ordering': ['-created_at'],
            },
        ),
    ]
