# Generated by Django 4.1.4 on 2023-02-11 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_page_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='keyword',
            field=models.CharField(default=0, max_length=20, verbose_name='Palabra clave'),
            preserve_default=False,
        ),
    ]
