# Generated by Django 4.1.4 on 2023-03-15 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='group',
            field=models.CharField(default=None, max_length=200, verbose_name='Grupo'),
        ),
    ]
