# Generated by Django 4.1.4 on 2022-12-28 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nombres')),
                ('profession', models.TextField(verbose_name='Profesión')),
                ('image', models.ImageField(upload_to='about', verbose_name='Imagen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'nosotros',
                'verbose_name_plural': 'nosotros',
                'ordering': ['-created_at'],
            },
        ),
    ]
