# Generated by Django 4.1.4 on 2023-03-15 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalcases',
            name='service',
            field=models.CharField(default='', max_length=200, verbose_name='Servicio'),
            preserve_default=False,
        ),
    ]
