# Generated by Django 4.1.4 on 2023-03-20 22:48

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_cases', '0002_clinicalcases_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalcases',
            name='image',
            field=models.ImageField(upload_to='clinical_cases', verbose_name='Imagen'),
        ),
        migrations.CreateModel(
            name='ClinicalCasesDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_image', models.ImageField(upload_to='clinical_cases', verbose_name='Primera imagen')),
                ('second_image', models.ImageField(upload_to='clinical_cases', verbose_name='Segunda imagen')),
                ('third_image', models.ImageField(upload_to='clinical_cases', verbose_name='Tercera imagen')),
                ('fourth_image', models.ImageField(upload_to='clinical_cases', verbose_name='Cuarta imagen')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Contenido')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('clinical_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinical_cases.clinicalcases')),
            ],
            options={
                'verbose_name': 'detalle de caso clínico',
                'verbose_name_plural': 'detalles de casos clínicos',
                'ordering': ['-created_at'],
            },
        ),
    ]
